/* ------------------------
 * WARNING: Please do not edit this file, as edits will be lost next time the tool is run.
 * ------------------------
 * 
 * This file was auto-generated by SqlBacked (https://github.com/msgooroo/SqlBacked), from:
 *
 * Database:	[{DATABASE_NAME}]
 * Schema name:	[{SCHEMA_NAME}]
 * Table name:	[{TABLE_NAME}]
 * 		
 * Created at:	[{TIME_STAMP}]
 * 
 * ------------------------
 */


using System;
using System.Linq;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.Threading;
using System.Threading.Tasks;

using MSGooroo.SqlBacked;

namespace [{NAMESPACE}] {

	[Serializable]
	public partial class [{TABLE_NAME}] : ITableBacked{

[{TABLE_NAME_PROPERTY}]
[{SCHEMA_NAME_PROPERTY}]
[{PRIMARY_KEY_PROPERTY}]

#region Properties
[{PROPERTIES}]
#endregion

#region SQL commands
[{INSERT_SQL}]

[{UPDATE_SQL}]
#endregion

#region Database binding
[{BIND_READER}]

[{BIND_COMMAND}]
#endregion

#region Get Methods
[{GET_METHODS}]

[{GET_CACHE_METHODS}]

[{GET_CACHE_SQL_METHODS}]

#endregion
	}
}