SELECT *
FROM (
	SELECT
		C.COLUMN_NAME,
		DATA_TYPE,
		IS_NULLABLE,
		CASE 
			WHEN DATA_TYPE = 'varchar' THEN 'string'
			WHEN DATA_TYPE = 'nvarchar' THEN 'string'
			WHEN DATA_TYPE = 'datetime' AND IS_NULLABLE = 'NO' THEN 'DateTime'
			WHEN DATA_TYPE = 'datetime' AND IS_NULLABLE = 'YES' THEN 'DateTime?'
			WHEN DATA_TYPE = 'smalldatetime' AND IS_NULLABLE = 'NO' THEN 'DateTime'
			WHEN DATA_TYPE = 'smalldatetime' AND IS_NULLABLE = 'YES' THEN 'DateTime?'
			WHEN DATA_TYPE = 'date' AND IS_NULLABLE = 'NO' THEN 'DateTime'
			WHEN DATA_TYPE = 'date' AND IS_NULLABLE = 'YES' THEN 'DateTime?'
			WHEN DATA_TYPE = 'int' AND IS_NULLABLE = 'YES' THEN 'int?'
			WHEN DATA_TYPE = 'int' AND IS_NULLABLE = 'NO' THEN 'int'
			WHEN DATA_TYPE = 'float' AND IS_NULLABLE = 'YES' THEN 'double?'
			WHEN DATA_TYPE = 'float' AND IS_NULLABLE = 'NO' THEN 'double'
			WHEN DATA_TYPE = 'smallint' AND IS_NULLABLE = 'NO' THEN 'Int16'
			WHEN DATA_TYPE = 'smallint' AND IS_NULLABLE = 'YES' THEN 'Int16?'
			WHEN DATA_TYPE = 'decimal' AND IS_NULLABLE = 'NO' THEN 'decimal'
			WHEN DATA_TYPE = 'decimal' AND IS_NULLABLE = 'YES' THEN 'decimal?'
			WHEN DATA_TYPE = 'numeric' AND IS_NULLABLE = 'NO' THEN 'decimal'
			WHEN DATA_TYPE = 'numeric' AND IS_NULLABLE = 'YES' THEN 'decimal?'
			WHEN DATA_TYPE = 'money' AND IS_NULLABLE = 'NO' THEN 'decimal'
			WHEN DATA_TYPE = 'money' AND IS_NULLABLE = 'YES' THEN 'decimal?'
			WHEN DATA_TYPE = 'bigint' AND IS_NULLABLE = 'NO' THEN 'long'
			WHEN DATA_TYPE = 'bigint' AND IS_NULLABLE = 'YES' THEN 'long?'
			WHEN DATA_TYPE = 'tinyint' AND IS_NULLABLE = 'NO' THEN 'byte'
			WHEN DATA_TYPE = 'tinyint' AND IS_NULLABLE = 'YES' THEN 'byte?'
			WHEN DATA_TYPE = 'uniqueidentifier' AND IS_NULLABLE = 'NO' THEN 'Guid'
			WHEN DATA_TYPE = 'uniqueidentifier' AND IS_NULLABLE = 'YES' THEN 'Guid?'
			WHEN DATA_TYPE = 'char' THEN 'string'
			WHEN DATA_TYPE = 'timestamp' THEN 'byte[]'
			WHEN DATA_TYPE = 'varbinary' THEN 'byte[]'
			WHEN DATA_TYPE = 'bit' AND IS_NULLABLE = 'NO' THEN 'bool'
			WHEN DATA_TYPE = 'bit' AND IS_NULLABLE = 'YES' THEN 'bool?'
			WHEN DATA_TYPE = 'xml' THEN 'string'
		END AS DOT_NET_TYPE, 
		CASE WHEN ID.COLUMN_NAME IS NULL THEN 0 ELSE 1 END AS IS_IDENTITY,
		CASE WHEN PK.COLUMN_NAME IS NULL THEN 0 ELSE 1 END AS IS_PK
				
		FROM INFORMATION_SCHEMA.COLUMNS C
		LEFT OUTER JOIN (
			SELECT IC.Name AS COLUMN_NAME
			FROM sys.identity_columns IC
			INNER JOIN sys.tables T
			ON T.object_id = IC.object_id
			INNER JOIN sys.schemas S
			ON T.schema_id = S.schema_id
			WHERE	T.name = @TABLE_NAME
			AND		S.name = @TABLE_SCHEMA
		) ID
		ON ID.COLUMN_NAME = C.COLUMN_NAME
		LEFT OUTER JOIN (
			SELECT K.COLUMN_NAME
			FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE K
			INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS C
			ON	K.TABLE_NAME = C.TABLE_NAME
			AND	K.TABLE_SCHEMA = C.TABLE_SCHEMA
			AND	K.CONSTRAINT_NAME = C.CONSTRAINT_NAME
			WHERE	C.TABLE_NAME = @TABLE_NAME
			AND		C.TABLE_SCHEMA = @TABLE_SCHEMA
			AND		C.CONSTRAINT_TYPE = 'PRIMARY KEY'
		) PK
		ON PK.COLUMN_NAME = C.COLUMN_NAME
		WHERE	TABLE_NAME = @TABLE_NAME
		AND		TABLE_SCHEMA = @TABLE_SCHEMA
	) A
WHERE DOT_NET_TYPE IS NOT NULL